import '@repo/ui/styles.css';
import './styles/globals.css';
import { Nanum_Gothic } from 'next/font/google';

import WithProviders from './providers/index';
import { NextProgress } from './lib/NextProgress';
import { AuthInitializer } from '@/web/app/middleware/auth-initializer';

import type { Metadata } from 'next';

const nanumGothic = Nanum_Gothic({
  weight: ['400', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};

import { AuthProvider } from '@/web/shared/model';
import type { GetApiUsersMeQueryResponse } from '@repo/api';

export default function App({
  children,
  user,
}: {
  children: React.ReactNode;
  user: GetApiUsersMeQueryResponse | null;
}) {
  console.log('App ::::::: ', user ? 'Authenticated' : 'Guest');
  return (
    <html lang="ko" className="dark" style={{ colorScheme: 'dark' }}>
      <body className={nanumGothic.className}>
        <WithProviders>
          <AuthProvider initialUser={user}>
            <AuthInitializer />
            <NextProgress />
            {children}
          </AuthProvider>
        </WithProviders>
      </body>
    </html>
  );
}
