import '@repo/ui/styles.css';
import './styles/globals.css';
import { Nanum_Gothic } from 'next/font/google';

import WithProviders from './providers/index';
import { NextProgress } from './lib/NextProgress';
import { Toaster } from '@/web/shared/ui';

import type { Metadata } from 'next';

const nanumGothic = Nanum_Gothic({
  weight: ['400', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};

export default function App({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body className={nanumGothic.className}>
        <WithProviders>
          <NextProgress />
          {children}
          <Toaster />
        </WithProviders>
      </body>
    </html>
  );
}
